export default {
  auth: {
    ACCESS_KEY_ID: "YOUR_AWS_USER_ACCESS_KEY_ID",
    SECRET_ACCESS_KEY: "YOUR_AWS_USER_SECRET_ACCESS_KEY"
  },
  apiGateway: {
    REGION: "YOUR_API_GATEWAY_REGION",
    URL: "YOUR_API_GATEWAY_URL",
    API_KEY: "YOUR_API_GATEWAY_API_KEY"
  }
};
